import { Provider, Category } from './types';
import { Truck, Box, Activity } from 'lucide-react';

export const CATEGORIES: Category[] = [
  { 
    id: 'courier', 
    name: 'Courier & Logistics', 
    description: 'Delivery tracking, order management, and logistics services for Bangladesh.', 
    icon: Truck 
  }
];

export const PROVIDERS: Provider[] = [
  {
    id: 'pathao',
    name: 'Pathao Courier',
    category: 'courier',
    color: '#e8394d',
    logoChar: 'P',
    logoUrl: 'https://merchant.pathao.com/assets/logo_pathao_courier.a3ef9b7c.svg',
    authType: 'OAuth 2.0',
    version: 'v1',
    description: 'Leading logistics provider in Bangladesh with OAuth 2.0 security.',
    weightUnit: 'kg',
    sandbox: {
      baseUrl: 'https://courier-api-sandbox.pathao.com',
      credentials: [
        { label: 'client_id', value: '7N1aMJQbWm' },
        { label: 'client_secret', value: 'wRcaibZkUdSNz2EI9ZyuXLlNrnAv0TdPUPXMnD39' },
        { label: 'username', value: 'test@pathao.com' },
        { label: 'password', value: 'lovePathao' }
      ]
    },
    production: {
      baseUrl: 'https://api-hermes.pathao.com',
      credentials: [
        { label: 'client_id', value: '8mepQVNaMy' },
        { label: 'client_secret', value: '(Retrieve from Merchant Dashboard)' }
      ]
    },
    callouts: [
      {
        type: 'warning',
        title: 'Token Expiry',
        message: 'Save both tokens to your database. Access token expires in 432000 seconds (5 days).'
      }
    ],
    groups: [
      {
        name: 'Auth',
        endpoints: [
          {
            id: 'pathao-issue-token',
            method: 'POST',
            path: '/aladdin/api/v1/issue-token',
            title: 'Issue Access Token',
            description: 'Obtain a Bearer token for authentication. Use grant_type="password".',
            bodyParams: [
              { field: 'client_id', type: 'string', required: true, description: 'Test/Production environment Client Id.' },
              { field: 'client_secret', type: 'string', required: true, description: 'Test/Production environment Client Secret.' },
              { field: 'grant_type', type: 'string', required: true, description: 'Must use grant type password for issue token api.' },
              { field: 'username', type: 'string', required: true, description: 'Test environment/your login email address.' },
              { field: 'password', type: 'string', required: true, description: 'Test environment/your login password.' }
            ],
            responseExample: JSON.stringify({ token_type: "Bearer", expires_in: 432000, access_token: "ISSUED_ACCESS_TOKEN", refresh_token: "ISSUED_REFRESH_TOKEN" }, null, 2)
          },
          {
            id: 'pathao-refresh-token',
            method: 'POST',
            path: '/aladdin/api/v1/issue-token',
            title: 'Issue Access Token from Refresh Token',
            description: 'Obtain a new access token using your refresh token. Use grant_type="refresh_token".',
            bodyParams: [
              { field: 'client_id', type: 'string', required: true, description: 'Your Client Id generated by Pathao Courier.' },
              { field: 'client_secret', type: 'string', required: true, description: 'Your Client Secret generated by Pathao Courier.' },
              { field: 'grant_type', type: 'string', required: true, description: 'Must use grant type refresh_token for refresh token api.' },
              { field: 'refresh_token', type: 'string', required: true, description: 'Provide your refresh token in order to generate access_token' }
            ],
            responseExample: JSON.stringify({ token_type: "Bearer", expires_in: 432000, access_token: "ISSUED_ACCESS_TOKEN", refresh_token: "ISSUED_REFRESH_TOKEN" }, null, 2)
          }
        ]
      },
      {
        name: 'Price Calculation',
        endpoints: [
           {
            id: 'pathao-price-plan',
            method: 'POST',
            path: '/aladdin/api/v1/merchant/price-plan',
            title: 'Price Calculation Api',
            description: 'To calculate price of the order use this post api.',
            bodyParams: [
              { field: 'store_id', type: 'integer', required: true, description: 'store_id is provided by the merchant and not changeable. This store ID will set the pickup location of the order according to the location of the store.' },
              { field: 'item_type', type: 'integer', required: true, description: '1 for Document, 2 for Parcel' },
              { field: 'delivery_type', type: 'integer', required: true, description: '48 for Normal Delivery, 12 for On Demand Delivery' },
              { field: 'item_weight', type: 'float', required: true, description: 'Minimum 0.5 KG to Maximum 10 kg. Weight of your parcel in kg' },
              { field: 'recipient_city', type: 'integer', required: true, description: 'Parcel receivers city_id' },
              { field: 'recipient_zone', type: 'integer', required: true, description: 'Parcel receivers zone_id' }
            ],
            responseExample: JSON.stringify({
              message: "price",
              type: "success",
              code: 200,
              data: {
                price: 80,
                discount: 0,
                promo_discount: 0,
                plan_id: 69,
                cod_enabled: 1,
                cod_percentage: 0.01,
                additional_charge: 0,
                final_price: 80
              }
            }, null, 2)
          }
        ]
      },
      {
        name: 'Orders',
        endpoints: [
          {
            id: 'pathao-create-order',
            method: 'POST',
            path: '/aladdin/api/v1/orders',
            title: 'Create a New Order',
            description: 'Create a new delivery order. Recipient location fields (city/zone/area) are optional but recommended; system will populate them based on address if omitted.',
            bodyParams: [
              { field: 'store_id', type: 'integer', required: true, description: 'store_id is provided by the merchant and not changeable. This store ID will set the pickup location of the order according to the location of the store.' },
              { field: 'merchant_order_id', type: 'string', required: false, description: 'Optional parameter, merchant order info/tracking id' },
              { field: 'recipient_name', type: 'string', required: true, description: 'Parcel receivers name. Name length should be between 3 to 100 characters.' },
              { field: 'recipient_phone', type: 'string', required: true, description: 'Parcel receivers contact number. Recipient phone length should be 11 characters.' },
              { field: 'recipient_secondary_phone', type: 'string', required: false, description: 'Parcel receivers secondary contact number. Recipient secondary phone length should be 11 characters. This field is optional.' },
              { field: 'recipient_address', type: 'string', required: true, description: 'Parcel receivers full address. Address length should be between 10 to 220 characters.' },
              { field: 'recipient_city', type: 'integer', required: false, description: "Parcel receiver's city_id. This is an optional parameter, so do not send a null value. If not included in the request payload, then our system will populate it automatically based on the recipient_address you will be provided." },
              { field: 'recipient_zone', type: 'integer', required: false, description: "Parcel receiver's zone_id. This is an optional parameter, so do not send a null value. If not included in the request payload, then our system will populate it automatically based on the recipient_address you will be provided." },
              { field: 'recipient_area', type: 'integer', required: false, description: "Parcel receiver's area_id. This is an optional parameter. If not included in the request payload, then our system will populate it automatically based on the recipient_address you will be provided." },
              { field: 'delivery_type', type: 'integer', required: true, description: '48 for Normal Delivery, 12 for On Demand Delivery' },
              { field: 'item_type', type: 'integer', required: true, description: '1 for Document, 2 for Parcel' },
              { field: 'special_instruction', type: 'string', required: false, description: 'Any special instruction you may want to provide to us.' },
              { field: 'item_quantity', type: 'integer', required: true, description: 'Quantity of your parcels' },
              { field: 'item_weight', type: 'float', required: true, description: 'Minimum 0.5 KG to Maximum 10 kg. Weight of your parcel in kg' },
              { field: 'item_description', type: 'string', required: false, description: 'You can provide a description of your parcel' },
              { field: 'amount_to_collect', type: 'integer', required: true, description: 'Recipient Payable Amount. Default should be 0 in case of NON Cash-On-Delivery(COD)The collectible amount from the customer.' }
            ],
            responseExample: JSON.stringify({ message: "Order Created Successfully", type: "success", code: 200, data: { consignment_id: "{{ORDER_CONSIGNMENT_ID}}", merchant_order_id: "{{merchant_order_id}}", order_status: "Pending", delivery_fee: 80 } }, null, 2)
          },
          {
            id: 'pathao-bulk-order',
            method: 'POST',
            path: '/aladdin/api/v1/orders/bulk',
            title: 'Create a Bulk Order',
            description: 'Create multiple orders at a time. Returns 202 immediately. Orders processed asynchronously.',
            bodyParams: [
              { field: 'orders', type: 'array', required: true, description: 'An array of order objects is required to send within the request body.' }
            ],
            bodyExample: JSON.stringify({
              orders: [
                {
                  store_id: 123,
                  merchant_order_id: "ORD-001",
                  recipient_name: "Demo Recipient One",
                  recipient_phone: "017XXXXXXXX",
                  recipient_address: "House 123, Road 4, Sector 10, Uttara, Dhaka",
                  delivery_type: 48,
                  item_type: 2,
                  special_instruction: "Do not put water",
                  item_quantity: 2,
                  item_weight: 0.5,
                  amount_to_collect: 100,
                  item_description: "Cloth item"
                },
                {
                  store_id: 123,
                  merchant_order_id: "ORD-002",
                  recipient_name: "Demo Recipient Two",
                  recipient_phone: "015XXXXXXXX",
                  recipient_address: "House 3, Road 14, Dhanmondi, Dhaka",
                  delivery_type: 48,
                  item_type: 2,
                  item_quantity: 1,
                  item_weight: 0.5,
                  amount_to_collect: 200
                }
              ]
            }, null, 2),
            responseExample: JSON.stringify({ message: "Your bulk order creation request is accepted,<br>  please wait some time to complete order creation.", type: "success", code: 202, data: true }, null, 2)
          },
          {
             id: 'pathao-order-info',
             method: 'GET',
             path: '/aladdin/api/v1/orders/{consignment_id}/info',
             title: 'Get Order Short Info',
             description: 'Get a short summary of your specific order.',
             pathParams: [{ field: 'consignment_id', type: 'string', required: true, description: 'This unique id is used to identify the consignment.' }],
             responseExample: JSON.stringify({ message: "Order info", type: "success", code: 200, data: { consignment_id: "{{consignment_id}}", merchant_order_id: "{{merchant_order_id}}", order_status: "Pending", order_status_slug: "Pending", updated_at: "2024-11-20 15:11:40", invoice_id: null } }, null, 2)
          }
        ]
      },
      {
        name: 'Stores',
        endpoints: [
          {
            id: 'pathao-create-store',
            method: 'POST',
            path: '/aladdin/api/v1/stores',
            title: 'Create a New Store',
            description: 'Create a new store for pickup.',
            bodyParams: [
              { field: 'name', type: 'string', required: true, description: 'Name of the store. Store name length should be between 3 to 50 characters.' },
              { field: 'contact_name', type: 'string', required: true, description: 'Contact person of the store need for issue related communication. Contact person name length should be between 3 to 50 characters.' },
              { field: 'contact_number', type: 'string', required: true, description: 'Store contact person phone number. Contact number length should be 11 characters.' },
              { field: 'secondary_contact', type: 'string', required: false, description: 'Store contact person secondary phone number. Secondary contact number length should be 11 characters. This field is optional.' },
              { field: 'otp_number', type: 'string', required: false, description: 'OTP for orders from this order will be sent to this number' },
              { field: 'address', type: 'string', required: true, description: 'Merchant Store address. Address length should be between 15 to 120 characters.' },
              { field: 'city_id', type: 'integer', required: true, description: 'Recipient city_id' },
              { field: 'zone_id', type: 'integer', required: true, description: 'Recipient zone_id' },
              { field: 'area_id', type: 'integer', required: true, description: 'Recipient area_id' }
            ],
            responseExample: JSON.stringify({ message: "Store created successfully, Please wait one hour for approval.", type: "success", code: 200, data: { store_name: "Demo Store" } }, null, 2)
          },
          {
            id: 'pathao-stores',
            method: 'GET',
            path: '/aladdin/api/v1/stores',
            title: 'Get Merchant Store Info',
            description: 'Get a summary of your current stores.',
            responseExample: JSON.stringify({ 
              message: "Store list fetched.",
              type: "success",
              code: 200,
              data: {
                data: [
                   {
                      store_id: 12345,
                      store_name: "My Store Name",
                      store_address: "House 123, Road 4, Sector 10, Uttara, Dhaka-1230, Bangladesh",
                      is_active: 1,
                      city_id: 1,
                      zone_id: 101,
                      hub_id: 50,
                      is_default_store: false,
                      is_default_return_store: false
                   }
                ],
                total: 1,
                current_page: 1,
                per_page: 1000,
                total_in_page: 1,
                last_page: 1,
                path: "https://api-hermes.pathao.com/aladdin/api/v1/stores",
                to: 1,
                from: 1,
                last_page_url: "https://api-hermes.pathao.com/aladdin/api/v1/stores?page=1",
                first_page_url: "https://api-hermes.pathao.com/aladdin/api/v1/stores?page=1"
              }
            }, null, 2)
          }
        ]
      },
      {
        name: 'Location',
        endpoints: [
          {
            id: 'pathao-cities',
            method: 'GET',
            path: '/aladdin/api/v1/city-list',
            title: 'Get List of Cities',
            description: 'Get all available cities.',
            responseExample: JSON.stringify({ message: "City successfully fetched.", type: "success", code: 200, data: { data: [ { city_id: 1, city_name: "Dhaka" }, { city_id: 2, city_name: "Chittagong" } ] } }, null, 2)
          },
          {
            id: 'pathao-zones',
            method: 'GET',
            path: '/aladdin/api/v1/cities/{city_id}/zone-list',
            title: 'Get Zones in City',
            description: 'Get list of zones within a particular city.',
            pathParams: [{ field: 'city_id', type: 'integer', required: true, description: 'A unique identifier for the city' }],
            responseExample: JSON.stringify({ message: "Zone list fetched.", type: "success", code: 200, data: { data: [ { zone_id: 298, zone_name: "60 feet" }, { zone_id: 1070, zone_name: "Abdullahpur Uttara" } ] } }, null, 2)
          },
           {
            id: 'pathao-areas',
            method: 'GET',
            path: '/aladdin/api/v1/zones/{zone_id}/area-list',
            title: 'Get Areas in Zone',
            description: 'Get list of areas within a particular zone.',
            pathParams: [{ field: 'zone_id', type: 'integer', required: true, description: 'A unique identifier for the zone' }],
            responseExample: JSON.stringify({ message: "Area list fetched.", type: "success", code: 200, data: { data: [ { area_id: 37, area_name: " Bonolota", home_delivery_available: true, pickup_available: true }, { area_id: 3, area_name: " Road 03", home_delivery_available: true, pickup_available: true } ] } }, null, 2)
          }
        ]
      }
    ]
  },
  {
    id: 'redx',
    name: 'RedX',
    category: 'courier',
    color: '#e83232',
    logoChar: 'R',
    logoUrl: 'https://redx.com.bd/images/new-redx-logo.svg',
    authType: 'Static JWT',
    version: 'v1.0.0-beta',
    description: 'Tech-first logistics with static JWT authentication.',
    weightUnit: 'g',
    sandbox: {
      baseUrl: 'https://sandbox.redx.com.bd/v1.0.0-beta',
      credentials: [
        { label: 'Token', value: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzM1NTMxNjU2LCJpc3MiOiJ0OTlnbEVnZTBUTm5MYTNvalh6MG9VaGxtNEVoamNFMyIsInNob3BfaWQiOjEsInVzZXJfaWQiOjZ9.zpKfyHK6zPBVaTrYevnCqnUA-e2jFKQJ7lK-z4aOx2g' }
      ]
    },
    production: {
      baseUrl: 'https://openapi.redx.com.bd/v1.0.0-beta',
      credentials: [
        { label: 'Token', value: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NjAzNjgiLCJpYXQiOjE3NzEzMDIzNjEsImlzcyI6InhBN3JRejVubmNwa05XZTAyRVM3ZUE4UkVSSGdHSVRIIiwic2hvcF9pZCI6OTYwMzY4LCJ1c2VyX2lkIjoxMjAxNjQ0fQ.dc2TCOwiHbZm1Jq5E3egZkZ_f1SafvoYyNSVsgeCPFY' }
      ]
    },
    callouts: [
      {
        type: 'info',
        title: 'Authentication',
        message: 'RedX uses a static JWT token. Add it as header: `API-ACCESS-TOKEN: Bearer {token}`.'
      }
    ],
    webhooks: {
      events: [
        { name: 'ready-for-delivery', description: 'Parcel received from merchants' },
        { name: 'delivery-in-progress', description: 'Parcels have been dispatched to rider' },
        { name: 'delivered', description: 'Parcels delivered by rider' },
        { name: 'agent-hold', description: 'Parcels are on hold to agent' },
        { name: 'agent-returning', description: 'Parcel return-in-progress' },
        { name: 'returned', description: 'Parcels returned' },
        { name: 'agent-area-change', description: 'Area change requested & in progress' }
      ],
      payloadExample: JSON.stringify({
        tracking_number: "REDX-12345",
        timestamp: "2023-10-25T10:00:00Z",
        status: "delivered",
        message_en: "Delivered Successfully",
        message_bn: "পার্সেলটি সফলভাবে ডেলিভার হয়েছে",
        invoice_number: "INV-123"
      }, null, 2)
    },
    groups: [
      {
        name: 'Parcels',
        endpoints: [
          {
            id: 'redx-track',
            method: 'GET',
            path: '/parcel/track/{tracking_id}',
            title: 'Track Parcel',
            pathParams: [{ field: 'tracking_id', type: 'string', required: true, description: 'Unique identifier assigned to a parcel for tracking.' }],
            responseExample: JSON.stringify({ tracking: [ { message_en: 'Package is created successfully', message_bn: 'পার্সেলটি সফল ভাবে প্লেস করা হয়েছে', time: '2020-02-04T21:19:41.000Z' }, { message_en: 'Package is picked up', message_bn: 'পার্সেল পিকাপ সম্পন্ন হয়েছে ', time: '2020-02-05T11:41:03.000Z' } ] }, null, 2)
          },
          {
            id: 'redx-parcel-info',
            method: 'GET',
            path: '/parcel/info/{tracking_id}',
            title: 'Get Parcel Details',
            pathParams: [{ field: 'tracking_id', type: 'string', required: true, description: 'Unique identifier assigned to a parcel for tracking.' }],
            responseExample: JSON.stringify({ parcel: { tracking_id: '21A427TU4BN3R', customer_address: 'Test Address', delivery_area: 'Mirpur DOHS', delivery_area_id: 12, charge: 60, customer_name: 'Test Customer', customer_phone: '01987654321', cash_collection_amount: 13293, parcel_weight: 500, merchant_invoice_id: 'ACBD1234TEST', status: 'pickup-pending', instruction: '', created_at: '2021-04-27T08:29:14.000Z', delivery_type: 'regular', value: '0', pickup_location: { id: 1, name: 'Malibag', address: 'Malibagh', area_name: 'Malibag', area_id: 1 } } }, null, 2)
          },
          {
            id: 'redx-create-parcel',
            method: 'POST',
            path: '/parcel',
            title: 'Create Parcel',
            description: 'Create a new parcel for delivery.',
            bodyParams: [
              { field: 'customer_name', type: 'string', required: true, description: 'Full name of the customer receiving the parcel.' },
              { field: 'customer_phone', type: 'string', required: true, description: 'Contact phone number of the customer.' },
              { field: 'delivery_area', type: 'string', required: true, description: 'Name of the delivery area where the parcel will be sent.' },
              { field: 'delivery_area_id', type: 'integer', required: true, description: 'Unique identifier of the delivery area.' },
              { field: 'customer_address', type: 'string', required: true, description: 'Complete address of the customer for parcel delivery.' },
              { field: 'cash_collection_amount', type: 'string', required: true, description: 'Amount to be collected from the customer upon delivery.' },
              { field: 'parcel_weight', type: 'string', required: true, description: 'Weight of the parcel in appropriate units (e.g., kg, g).' },
              { field: 'value', type: 'string', required: true, description: 'Declared value of the parcel for compensation calculation.' },
              { field: 'merchant_invoice_id', type: 'string', required: false, description: 'Invoice ID generated by the merchant for reference.' },
              { field: 'instruction', type: 'string', required: false, description: 'Special instructions for the delivery (if any).' },
              { field: 'type', type: 'string', required: false, description: 'Defines the parcel type, mainly used for reverse shipments.' },
              { field: 'is_closed_box', type: 'string', required: false, description: 'Whether the parcel is a closed box.' },
              { field: 'pickup_store_id', type: 'integer', required: false, description: 'Identifier of the pickup store where the parcel is collected from.' },
              { field: 'parcel_details_json', type: 'array', required: false, description: 'JSON object containing additional parcel details.' }
            ],
            bodyExample: JSON.stringify({
                customer_name: "Test Customer",
                customer_phone: "01700000000",
                delivery_area: "Gulshan",
                delivery_area_id: 12,
                customer_address: "House 12, Road 3",
                merchant_invoice_id: "ACBD1234TEST",
                cash_collection_amount: "1500",
                parcel_weight: 500,
                instruction: "Handle with care",
                value: 1500,
                is_closed_box: "0",
                pickup_store_id: 1,
                parcel_details_json: [
                    { name: "Shirt", category: "Clothing", value: 1500 },
                    { name: "Pants", category: "Clothing", value: 1200 }
                ]
            }, null, 2),
            responseExample: JSON.stringify({ tracking_id: "20A312THJDJ8" }, null, 2)
          },
          {
            id: 'redx-update-parcel',
            method: 'PATCH',
            path: '/parcels',
            title: 'Update Parcel',
            description: 'Update parcel status or details.',
            bodyParams: [
              { field: 'entity_type', type: 'string', required: true, description: "Type of entity being updated, e.g., 'parcel-tracking-id'." },
              { field: 'entity_id', type: 'string', required: true, description: 'Unique identifier of the parcel to be updated.' },
              { field: 'update_details', type: 'object', required: true, description: 'Object containing details of the update to be applied.' }
            ],
            responseExample: JSON.stringify({ success: true, message: "Request Accepted" }, null, 2)
          }
        ]
      },
      {
        name: 'Logistics',
        endpoints: [
          {
            id: 'redx-areas',
            method: 'GET',
            path: '/areas',
            title: 'Get Areas',
            description: 'Get all areas, or filter by postal code / district.',
            queryParams: [
              { field: 'post_code', type: 'integer', required: false, description: 'The postal code for which areas need to be retrieved.' },
              { field: 'district_name', type: 'string', required: false, description: 'The name of the district for which areas need to be retrieved.' }
            ],
            responseExample: JSON.stringify({ areas: [ { id: 1, name: "Mohammadpur(Dhaka)", post_code: 1207, division_name: "Dhaka", zone_id: 1 } ] }, null, 2)
          },
          {
            id: 'redx-charge-calculator',
            method: 'GET',
            path: '/charge/charge_calculator',
            title: 'Calculate Parcel Charge',
            queryParams: [
               { field: 'delivery_area_id', type: 'integer', required: true, description: 'The unique identifier of the area where the parcel will be delivered.' },
               { field: 'pickup_area_id', type: 'integer', required: true, description: 'The unique identifier of the area where the parcel will be picked up.' },
               { field: 'cash_collection_amount', type: 'integer', required: true, description: 'The total cash amount to be collected upon delivery.' },
               { field: 'weight', type: 'integer', required: true, description: 'The weight of the parcel in grams.' }
            ],
            responseExample: JSON.stringify({ deliveryCharge: 60, codCharge: 0 }, null, 2)
          }
        ]
      },
      {
        name: 'Pickup Stores',
        endpoints: [
           {
            id: 'redx-create-pickup-store',
            method: 'POST',
            path: '/pickup/store',
            title: 'Create Pickup Store',
            bodyParams: [
              { field: 'name', type: 'string', required: true, description: 'The name of the pickup store.' },
              { field: 'phone', type: 'string', required: true, description: 'The contact phone number for the pickup store.' },
              { field: 'address', type: 'string', required: true, description: 'The physical address of the pickup store.' },
              { field: 'area_id', type: 'integer', required: true, description: 'The unique identifier of the area where the pickup store is located.' }
            ],
            responseExample: JSON.stringify({ id: 1, name: "Test Pickup Store", address: "Test Address", area_id: 1, area_name: "Malibag", phone: "01700000000" }, null, 2)
           },
           {
            id: 'redx-get-pickup-stores',
            method: 'GET',
            path: '/pickup/stores',
            title: 'Get Pickup Stores',
            responseExample: JSON.stringify({ pickup_stores: [ { id: 1, name: "Store 1", address: "Address 1", area_name: "Malibag", area_id: 1, phone: "01700000000", created_at: "2021-04-27T08:29:14.000Z" } ] }, null, 2)
           },
           {
            id: 'redx-pickup-store-info',
            method: 'GET',
            path: '/pickup/store/info/{pickup_store_id}',
            title: 'Pickup Store Details',
            pathParams: [{ field: 'pickup_store_id', type: 'integer', required: true, description: 'The unique identifier of the pickup store whose details need to be retrieved.' }],
            responseExample: JSON.stringify({ pickup_store: { id: 1, name: "Test Store", address: "Dhaka", phone: "01700000000", area_name: "Malibag", area_id: 1, created_at: "2021-04-27T08:29:14.000Z" } }, null, 2)
           }
        ]
      }
    ]
  },
  {
    id: 'steadfast',
    name: 'Steadfast Courier',
    category: 'courier',
    color: '#1a73e8',
    logoChar: 'S',
    logoUrl: 'https://merchant.packzy.com/assets/images/logo/logo.svg',
    authType: 'API Key',
    version: 'v1',
    description: 'Simple API Key authentication. No tokens required.',
    weightUnit: 'kg', // N/A effectively, but keeping type consistent
    sandbox: null, // No sandbox
    production: {
      baseUrl: 'https://portal.packzy.com/api/v1',
      credentials: [
        { label: 'Api-Key', value: '(Retrieve from Steadfast Dashboard)' },
        { label: 'Secret-Key', value: '(Retrieve from Steadfast Dashboard)' },
        { label: 'Content-Type', value: 'application/json' }
      ]
    },
    callouts: [
      {
        type: 'tip',
        title: 'Simple Auth',
        message: 'Just add Api-Key and Secret-Key headers to every request.'
      },
      {
        type: 'warning',
        title: 'Bulk Order Format',
        message: 'For bulk orders, the payload is a JSON object with a single "data" key, containing an array of order objects.'
      }
    ],
    statuses: [
      { slug: 'pending', meaning: 'Consignment is not delivered or cancelled yet.' },
      { slug: 'delivered_approval_pending', meaning: 'Consignment is delivered but waiting for admin approval.' },
      { slug: 'partial_delivered_approval_pending', meaning: 'Consignment is delivered partially and waiting for admin approval.' },
      { slug: 'cancelled_approval_pending', meaning: 'Consignment is cancelled and waiting for admin approval.' },
      { slug: 'unknown_approval_pending', meaning: 'Unknown Pending status. Need contact with the support team.' },
      { slug: 'delivered', meaning: 'Consignment is delivered and balance added.' },
      { slug: 'partial_delivered', meaning: 'Consignment is partially delivered and balance added.' },
      { slug: 'cancelled', meaning: 'Consignment is cancelled and balance updated.' },
      { slug: 'hold', meaning: 'Consignment is held.' },
      { slug: 'in_review', meaning: 'Order is placed and waiting to be reviewed.' },
      { slug: 'unknown', meaning: 'Unknown status. Need contact with the support team.' }
    ],
    groups: [
      {
        name: 'Orders',
        endpoints: [
          {
            id: 'steadfast-create',
            method: 'POST',
            path: '/create_order',
            title: 'Placing an order',
            description: 'Create a new consignment order.',
            bodyParams: [
              { field: 'invoice', type: 'string', required: true, description: 'Must be Unique and can be alpha-numeric including hyphens and underscores.' },
              { field: 'recipient_name', type: 'string', required: true, description: 'Within 100 characters.' },
              { field: 'recipient_phone', type: 'string', required: true, description: 'Must be 11 Digits Phone number.' },
              { field: 'alternative_phone', type: 'string', required: false, description: 'Must be 11 Digits Phone number.' },
              { field: 'recipient_email', type: 'string', required: false, description: 'Recipient email address.' },
              { field: 'recipient_address', type: 'string', required: true, description: 'Recipient’s address within 250 characters.' },
              { field: 'cod_amount', type: 'numeric', required: true, description: "Cash on delivery amount in BDT including all charges. Can't be less than 0." },
              { field: 'note', type: 'string', required: false, description: 'Delivery instructions or other notes.' },
              { field: 'item_description', type: 'string', required: false, description: 'Items name and other information' },
              { field: 'total_lot', type: 'numeric', required: false, description: 'Total Lot of items.' },
              { field: 'delivery_type', type: 'numeric', required: false, description: '0 = Home Delivery, 1 = Point Delivery/Steadfast Hub Pick Up.' }
            ],
            responseExample: JSON.stringify({
              status: 200,
              message: "Consignment has been created successfully.",
              consignment: {
                consignment_id: 1424107,
                invoice: "Aa12-das4",
                tracking_code: "15BAEB8A",
                recipient_name: "John Smith",
                recipient_phone: "01234567890",
                recipient_address: "Fla# A1,House# 17/1, Road# 3/A, Dhanmondi,Dhaka-1209",
                cod_amount: 1060,
                status: "in_review",
                note: "Deliver within 3PM",
                created_at: "2021-03-21T07:05:31.000000Z",
                updated_at: "2021-03-21T07:05:31.000000Z"
              }
            }, null, 2)
          },
          {
            id: 'steadfast-bulk',
            method: 'POST',
            path: '/create_order/bulk-order',
            title: 'Bulk Order Create',
            description: 'Maximum 500 items are allowed. Payload is a JSON object with a "data" key containing the array.',
            bodyParams: [
              { field: 'data', type: 'array', required: true, description: 'Array of order objects.' }
            ],
            bodyExample: JSON.stringify({
              data: [
                {
                   invoice: "123",
                   recipient_name: "John Doe",
                   recipient_address: "Address here",
                   recipient_phone: "01700000000",
                   cod_amount: 500,
                   note: "Urgent"
                },
                {
                   invoice: "124",
                   recipient_name: "Jane Doe",
                   recipient_address: "Address there",
                   recipient_phone: "01800000000",
                   cod_amount: 0,
                   note: "Prepaid"
                }
              ]
            }, null, 2),
            responseExample: JSON.stringify([
              {
                invoice: "230822-1",
                recipient_name: "John Doe",
                recipient_address: "House 44, Road 2/A, Dhanmondi, Dhaka 1209",
                recipient_phone: "0171111111",
                cod_amount: "0.00",
                note: null,
                consignment_id: 11543968,
                tracking_code: "B025A038",
                status: "success"
              }
            ], null, 2)
          }
        ]
      },
      {
        name: 'Status',
        endpoints: [
          {
            id: 'steadfast-status-cid',
            method: 'GET',
            path: '/status_by_cid/{id}',
            title: 'Check Status by Consignment ID',
            pathParams: [{ field: 'id', type: 'string', required: true, description: 'Consignment ID' }],
            responseExample: JSON.stringify({ status: 200, delivery_status: "in_review" }, null, 2)
          },
          {
            id: 'steadfast-status-invoice',
            method: 'GET',
            path: '/status_by_invoice/{invoice}',
            title: 'Check Status by Invoice ID',
            pathParams: [{ field: 'invoice', type: 'string', required: true, description: 'Your Invoice ID' }],
            responseExample: JSON.stringify({ status: 200, delivery_status: "delivered" }, null, 2)
          },
          {
            id: 'steadfast-status-tracking',
            method: 'GET',
            path: '/status_by_trackingcode/{trackingCode}',
            title: 'Check Status by Tracking Code',
            pathParams: [{ field: 'trackingCode', type: 'string', required: true, description: 'Tracking Code' }],
            responseExample: JSON.stringify({ status: 200, delivery_status: "cancelled" }, null, 2)
          }
        ]
      },
      {
        name: 'Account & Payments',
        endpoints: [
          {
            id: 'steadfast-balance',
            method: 'GET',
            path: '/get_balance',
            title: 'Checking Current Balance',
            responseExample: JSON.stringify({ status: 200, current_balance: 0 }, null, 2)
          },
          {
            id: 'steadfast-payments',
            method: 'GET',
            path: '/payments',
            title: 'Get Payments',
            description: 'Get list of payments.',
            responseExample: JSON.stringify({ payments: [] }, null, 2)
          },
          {
            id: 'steadfast-single-payment',
            method: 'GET',
            path: '/payments/{payment_id}',
            title: 'Get Single Payment with Consignments',
            pathParams: [{ field: 'payment_id', type: 'string', required: true, description: 'Payment ID' }],
            responseExample: JSON.stringify({ payment: { id: 123, amount: 5000, consignments: [] } }, null, 2)
          }
        ]
      },
      {
        name: 'Return Requests',
        endpoints: [
          {
             id: 'steadfast-create-return',
             method: 'POST',
             path: '/create_return_request',
             title: 'Creating Return Requests',
             bodyParams: [
                { field: 'consignment_id', type: 'numeric/string', required: true, description: 'Consignment id or user defined invoice id or tracking code of the consignment of the requesting consignment.' },
                { field: 'reason', type: 'string', required: false, description: 'Reason for return.' }
             ],
             responseExample: JSON.stringify({
                id: 1,
                user_id: 1,
                consignment_id: 10000042,
                reason: null,
                status: "pending",
                created_at: "2025-07-30T23:11:45.000000Z",
                updated_at: "2025-07-30T23:11:45.000000Z"
             }, null, 2)
          },
          {
             id: 'steadfast-get-return',
             method: 'GET',
             path: '/get_return_request/{id}',
             title: 'Single Return Request View',
             pathParams: [{ field: 'id', type: 'string', required: true, description: 'Return Request ID' }],
             responseExample: JSON.stringify({ id: 1, status: "pending" }, null, 2)
          },
          {
             id: 'steadfast-get-returns',
             method: 'GET',
             path: '/get_return_requests',
             title: 'Get Return Requests',
             responseExample: JSON.stringify({ data: [] }, null, 2)
          }
        ]
      },
      {
         name: 'General',
         endpoints: [
            {
               id: 'steadfast-police',
               method: 'GET',
               path: '/police_stations',
               title: 'Get Policestations',
               responseExample: JSON.stringify({ data: [] }, null, 2)
            }
         ]
      }
    ]
  },
  {
    id: 'carrybee',
    name: 'Carrybee',
    category: 'courier',
    color: '#f59e0b',
    logoChar: 'C',
    logoUrl: 'https://merchant.carrybee.com/_next/image?url=%2Fassets%2Fimages%2Flogo-with-tag.png&w=256&q=75',
    authType: 'Client Headers',
    version: 'v2.0',
    description: 'Context-aware client headers authentication.',
    weightUnit: 'g',
    sandbox: {
      baseUrl: 'https://stage-sandbox.carrybee.com',
      credentials: [
        { label: 'Client ID', value: '1a89c1a6-fc68-4395-9c09-628e0d3eaafc' },
        { label: 'Client Secret', value: '1d7152c9-5b2d-4e4e-9c20-652b93333704' },
        { label: 'Client Context', value: 'DzJwPsx31WaTbS745XZoBjmQLcNqwK' }
      ]
    },
    production: {
      baseUrl: 'https://developers.carrybee.com',
      credentials: [
        { label: 'Credentials', value: 'Available in dashboard' }
      ]
    },
    callouts: [
      {
        type: 'warning',
        title: 'Weight Unit',
        message: 'item_weight is in GRAMS not kilograms! 500 = 0.5kg.'
      },
      {
        type: 'tip',
        title: 'Validation',
        message: 'Search fields like query in address details must be >10 chars. Area search >3 chars.'
      }
    ],
    webhooks: {
      events: [
        { name: 'order.created', description: 'New order created' },
        { name: 'order.updated', description: 'Order details updated' },
        { name: 'order.pickup-requested', description: 'Pickup requested by merchant' },
        { name: 'order.assigned-for-pickup', description: 'Rider assigned for pickup' },
        { name: 'order.picked', description: 'Parcel collected from store' },
        { name: 'order.pickup-failed', description: 'Pickup failed' },
        { name: 'order.pickup-cancelled', description: 'Pickup cancelled' },
        { name: 'order.at-the-sorting-hub', description: 'Parcel at sorting hub' },
        { name: 'order.on-the-way-to-central-warehouse', description: 'Moving to central WH' },
        { name: 'order.at-central-warehouse', description: 'At Central Warehouse' },
        { name: 'order.in-transit', description: 'In transit to destination' },
        { name: 'order.received-at-last-mile-hub', description: 'At destination hub' },
        { name: 'order.assigned-for-delivery', description: 'Rider assigned for delivery' },
        { name: 'order.delivery-on-hold', description: 'Delivery on hold' },
        { name: 'order.delivered', description: 'Delivered successfully' },
        { name: 'order.partial-delivery', description: 'Partially delivered' },
        { name: 'order.delivery-failed', description: 'Delivery failed' },
        { name: 'order.returned', description: 'Returned to merchant' },
        { name: 'order.paid-return', description: 'Returned with payment' },
        { name: 'order.exchange', description: 'Order exchanged' },
        { name: 'order.paid', description: 'Payment settled' },
        { name: 'order.returned-at-sorting', description: 'Returned from sorting' },
        { name: 'order.returned-in-transit', description: 'Returned during transit' },
        { name: 'order.returned-to-merchant', description: 'Physically returned to merchant' }
      ],
      payloadExample: JSON.stringify({
         event: "order.created",
         store_id: "a1b2c3d4",
         consignment_id: "FX1212124433",
         merchant_order_id: "order-1234",
         timestamptz: "2025-07-30T10:11:12+00:00",
         collectable_amount: "1592",
         cod_fee: 15.92,
         delivery_fee: "85"
      }, null, 2),
      signatureHeader: 'X-Carrybee-Webhook-Signature',
      testCurl: `curl --location '{{webhook_url}}' \\
  --header 'X-Carrybee-Webhook-Signature: "{{WEBHOOK_SIGNATURE}}"' \\
  --data '{
    "content": "your webhook event data"
  }'`,
      testNote: '{{WEBHOOK_SIGNATURE}} is provided by you to Carrybee. Verify this header on your server.'
    },
    groups: [
      {
        name: 'Location',
        endpoints: [
          {
            id: 'carrybee-cities',
            method: 'GET',
            path: '/api/v2/cities',
            title: 'Get Cities',
            responseExample: JSON.stringify({ error: false, message: "City list fetched successfully", data: { cities: [{ id: 14, name: "Dhaka" }] } }, null, 2)
          },
          {
            id: 'carrybee-zones',
            method: 'GET',
            path: '/api/v2/cities/{city_id}/zones',
            title: 'Get Zones',
            pathParams: [{ field: 'city_id', type: 'integer', required: true, description: 'City ID' }],
            responseExample: JSON.stringify({ error: false, message: "Zones", data: { zones: [{ id: 290, name: "Zoo Road", city_id: 14 }] } }, null, 2)
          },
          {
            id: 'carrybee-areas',
            method: 'GET',
            path: '/api/v2/cities/{city_id}/zones/{zone_id}/areas',
            title: 'Get Areas',
            pathParams: [
              { field: 'city_id', type: 'integer', required: true, description: 'City ID' },
              { field: 'zone_id', type: 'integer', required: true, description: 'Zone ID' }
            ],
            responseExample: JSON.stringify({ error: false, message: "Area list fetched successfully", data: { areas: [{ id: 8803, name: "Zirani Kata", zone_id: 356 }] } }, null, 2)
          },
          {
            id: 'carrybee-area-suggestion',
            method: 'GET',
            path: '/api/v2/area-suggestion',
            title: 'Get Area Suggestion',
            description: 'Search for areas, zones, or cities. Min 3 chars.',
            queryParams: [{ field: 'search', type: 'string', required: true, description: 'Field search should be at least 3 characters long, allowing to search for the text in the area/zone/city.' }],
            responseExample: JSON.stringify({ error: false, data: { items: [{ city_id: 14, city_name: "Dhaka", zone_id: 161, zone_name: "Mirpur", area_id: 8803, area_name: "Alal Avenue" }] } }, null, 2)
          },
          {
            id: 'carrybee-address',
            method: 'POST',
            path: '/api/v2/address-details',
            title: 'Address Lookup',
            description: 'Get city_id and zone_id from an address string (min 10 chars).',
            bodyParams: [
              { field: 'query', type: 'string', required: true, description: 'Field query is required, and should be at least 10 characters long.' }
            ],
            responseExample: JSON.stringify({ error: false, message: "Address details", data: { city_id: 14, zone_id: 161 } }, null, 2)
          }
        ]
      },
      {
        name: 'Stores',
        endpoints: [
          {
            id: 'carrybee-create-store',
            method: 'POST',
            path: '/api/v2/stores',
            title: 'Create Store',
            bodyParams: [
               { field: 'name', type: 'string', required: true, description: 'name field should be between 3 and 30 characters.' },
               { field: 'contact_person_name', type: 'string', required: true, description: 'contact_person_name field should be between 3 and 30 characters.' },
               { field: 'contact_person_number', type: 'string', required: true, description: 'contact_person_number field should be a valid phone number.' },
               { field: 'contact_person_secondary_number', type: 'string', required: false, description: 'Optional. If present, must be a valid phone number.' },
               { field: 'address', type: 'string', required: true, description: 'address field should be between 3 and 100 characters.' },
               { field: 'city_id', type: 'integer', required: true, description: 'City ID' },
               { field: 'zone_id', type: 'integer', required: true, description: 'Zone ID' },
               { field: 'area_id', type: 'integer', required: true, description: 'Area ID' },
               { field: 'lat', type: 'float', required: false, description: 'Optional. Must be a valid latitude field.' },
               { field: 'lng', type: 'float', required: false, description: 'Optional. Must be a valid longitude field.' }
            ],
            responseExample: JSON.stringify({ error: false, message: "Store created successfully" }, null, 2)
          },
          {
            id: 'carrybee-get-stores',
            method: 'GET',
            path: '/api/v2/stores',
            title: 'Get All Stores',
            responseExample: JSON.stringify({ error: false, message: "Store list", data: { stores: [{ id: "abcd-1234", name: "Store of Anik", is_active: true }] } }, null, 2)
          }
        ]
      },
      {
        name: 'Orders',
        endpoints: [
          {
            id: 'carrybee-create',
            method: 'POST',
            path: '/api/v2/orders',
            title: 'Create Single Order',
            callouts: [
              {
                type: 'warning',
                title: 'API Typo Alert',
                message: 'The secondary phone field is spelled `recipient_secendary_phone` (not `secondary`) in the Carrybee API. Use the misspelled version exactly in your payload.'
              },
              {
                 type: 'info',
                 title: 'Weights',
                 message: 'item_weight must be in GRAMS (1-25000).'
              }
            ],
            bodyParams: [
              { field: 'store_id', type: 'string', required: true, description: 'Required. Should be string. Is the value (data.stores[*].id) from the Get list of stores response.' },
              { field: 'merchant_order_id', type: 'string', required: false, description: 'Optional. If present in the request, should be a string with length below 50 characters.' },
              { field: 'delivery_type', type: 'integer', required: true, description: 'Value should be 1 for Normal delivery, 2 for Express Delivery.' },
              { field: 'product_type', type: 'integer', required: true, description: 'Value should be 1 for Parcel, 2 for Book, 3 for Document.' },
              { field: 'recipient_name', type: 'string', required: true, description: 'The length between 2 and 99 characters.' },
              { field: 'recipient_phone', type: 'string', required: true, description: 'Must be a valid phone number string.' },
              { field: 'recipient_secendary_phone', type: 'string', required: false, description: 'Optional. If present, must be a valid phone number string.' },
              { field: 'recipient_address', type: 'string', required: true, description: 'The length between 10 and 200 characters.' },
              { field: 'city_id', type: 'integer', required: true, description: 'The value of (data.cities[*].id) from the Get cities response.' },
              { field: 'zone_id', type: 'integer', required: true, description: 'The value of (data.zones[*].id) from the Get zones response.' },
              { field: 'area_id', type: 'integer', required: false, description: 'Optional. The value of (data.areas[*].id) from the Get areas response.' },
              { field: 'item_weight', type: 'integer', required: true, description: 'An integer field. The value should be in GRAMS, not in KILOGRAMS. The value should be in between 1 and 25000.' },
              { field: 'item_quantity', type: 'integer', required: false, description: 'An integer field. The value should be in between 1 and 200.' },
              { field: 'collectable_amount', type: 'integer', required: false, description: 'Receives in Taka, is an optional and integer field. If present, value should be between 0 and 100000.' },
              { field: 'special_instruction', type: 'string', required: false, description: 'Optional. If present, the value should be a string and the length should be less then 256 characters.' },
              { field: 'product_description', type: 'string', required: false, description: 'Optional. If present, the value should be a string and the length should be less then 256 characters.' },
              { field: 'is_closed', type: 'boolean', required: false, description: 'Optional and boolean field (default: false). If an order is supposed to be a close box item, the field should be true.' }
            ],
            responseExample: JSON.stringify({ error: false, message: "Order Created Successfully", data: { order: { consignment_id: "FX1212124433", store_id: "a1b2c3d4", merchant_order_id: "order-1234", collectable_amount: "15000", cod_fee: 15, delivery_fee: "60" } } }, null, 2)
          },
          {
             id: 'carrybee-bulk',
             method: 'POST',
             path: '/api/v2/orders-bulk',
             title: 'Create Bulk Order',
             description: 'Accepts an array of order objects (same structure as single order).',
             bodyParams: [
                { field: 'orders', type: 'array', required: true, description: 'Array of order objects' }
             ],
             bodyExample: JSON.stringify({
                orders: [
                   {
                      store_id: "a1b2c3d4",
                      merchant_order_id: "order-1",
                      delivery_type: 1,
                      product_type: 1,
                      recipient_phone: "01700000000",
                      recipient_name: "John Doe",
                      recipient_address: "House 10, Road 5",
                      city_id: 14,
                      zone_id: 5,
                      item_weight: 500
                   },
                   {
                      store_id: "a1b2c3d4",
                      merchant_order_id: "order-2",
                      delivery_type: 1,
                      product_type: 1,
                      recipient_phone: "01800000000",
                      recipient_name: "Jane Doe",
                      recipient_address: "House 12, Road 3",
                      city_id: 14,
                      zone_id: 5,
                      item_weight: 1000
                   }
                ]
             }, null, 2),
             responseExample: JSON.stringify({ error: false, message: "Order list accepted to be processed" }, null, 2)
          },
          {
            id: 'carrybee-get-order',
            method: 'GET',
            path: '/api/v2/orders/{consignment_id}/details',
            title: 'Get Order Details',
            pathParams: [{ field: 'consignment_id', type: 'string', required: true, description: 'The consignment_id should either be our consignment id or the your tracking/booking id. In case you are using your tracking/booking id, the ID should be at least 3 characters long, also it should be path parameter friendly.' }],
            responseExample: JSON.stringify({ 
              error: false,
              message: "Order details",
              data: { 
                transfer_status: "In transit",
                consignment_id: "FX1212124433", 
                merchant_order_id: "order-1234",
                recipient_name: "John Doe",
                recipient_phone: "01700000000",
                recipient_secondary_phone: null,
                recipient_address: "House 10, Road 5",
                collectable_amount: "1000",
                collected_amount: "0",
                cod_fee: 10,
                delivery_fee: "105",
                attempt: 0,
                updated_at: "2025-07-30T10:11:12+00:00"
              } 
            }, null, 2)
          },
          {
            id: 'carrybee-cancel',
            method: 'POST',
            path: '/api/v2/orders/{consignment_id}/cancel',
            title: 'Cancel Order',
            pathParams: [{ field: 'consignment_id', type: 'string', required: true, description: 'Consignment ID' }],
            bodyParams: [
               { field: 'cancellation_reason', type: 'string', required: true, description: 'The value should contain less than 200 characters.' }
            ],
            responseExample: JSON.stringify({ error: false, message: "Order cancelled successfully" }, null, 2)
          }
        ]
      }
    ]
  }
];

export const COMPARISON_DATA = [
  { feature: 'Auth Type', pathao: 'OAuth 2.0', redx: 'Static JWT', steadfast: 'API Key', carrybee: 'Client Headers' },
  { feature: 'Token Refresh', pathao: 'Yes', redx: 'No', steadfast: 'No', carrybee: 'No' },
  { feature: 'Sandbox', pathao: 'Yes', redx: 'Yes', steadfast: 'No', carrybee: 'Yes' },
  { feature: 'Bulk Orders', pathao: 'Yes (async)', redx: 'No', steadfast: 'Yes (max 500)', carrybee: 'Yes (async)' },
  { feature: 'Webhooks', pathao: 'No', redx: 'Yes', steadfast: 'No', carrybee: 'Yes (20+)' },
  { feature: 'Weight Unit', pathao: 'kg', redx: 'grams', steadfast: 'N/A', carrybee: 'grams' },
  { feature: 'Price Calc API', pathao: 'Yes', redx: 'Yes', steadfast: 'No', carrybee: 'No' },
];